# Generated by Django 4.1.13 on 2023-12-05 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_song_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='nationality',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.country'),
        ),
    ]
